<?php 

/**
 * Implements hook_permission
 */


function progress_bar_permission() {
   return array(
      'access progress_bar submissions' => array(
      'title' => t('progress_bar submissions'),
      'description' => t('progress_bar submissions description'),
      ),
   );
}



/**
 * Implements hook_menu
 * http://137.122.91.41/progress-bar-submissions is page link for accessing progress bar submissions 
 */

function progress_bar_menu() {
  $items = array();

  $items['progress-bar-submissions'] = array(
    'title' => 'Progresss bar submissions',
    'page callback' => 'progress_bar_submissions',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('access progress_bar submissions'),
  );
  return $items;
}


/**
 * Implements hook_theme
 */

function progress_bar_theme($existing, $type, $theme, $path) {
    return array(
        'progress_bar_template' => array(
	    'variables' => array('statusForProgressBar' => 'Navigation Day'),
            'template' => 'progress_bar_template',          
        ),
    );
}


function progress_bar_submissions()
{
global $user;
$userId = $user->uid;
$submissionId = -1;
$status = 'Navigation Day';

$results = db_query("SELECT sid FROM {webform_submitted_data} WHERE data = '$userId' ORDER BY sid desc LIMIT 1");

foreach($results AS $result) {
$submissionId = $result->sid;
}

if ($submissionId != (-1)) {
$resultsQuery2 = db_query("SELECT data FROM webform_submitted_data WHERE sid = '$submissionId' AND cid = 3 order by sid desc LIMIT 1");

foreach($resultsQuery2 AS $resultQuery2) {
$status = $resultQuery2->data;
}
}

$output = array(
	'#theme' => 'progress_bar_template',
	'#type' => 'markup',
	'#statusForProgressBar' => $status,
	);

return $output;
}
